<?
$aMenuLinks = Array(
    Array(
        "Кошельки",
        "/about/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Клатчи",
        "/shops/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Обложки для документов",
        "/blog/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Браслеты",
        "/delivery/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Визитницы",
        "/delivery/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Ключницы",
        "/delivery/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Картхолдеры",
        "/delivery/",
        Array(),
        Array(),
        ""
    ),
);
?>